:dynamic: true
:concurrency: 25
:pidfile: tmp/pids/sidekiq.pid

:queues:
  - active_storage_analysis
  - active_storage_purge
  - lokic
  - story_type
  - cron_tab
  - scrape_task
  - article_type
  - work_request

:schedule:
  initial:
    in: '0s'
    queue: cron_tab
    class: CronTabInitializerJob
