:dynamic: true

:concurrency: 30

:queues:
  - active_storage_analysis
  - active_storage_purge
  - lokic
  - story_type

:schedule:
  initialize:
    in: '0s'
    queue: lokic
    class: CronTabInitializerJob
