:dynamic: true
:concurrency: 50

:queues:
  - active_storage_analysis
  - active_storage_purge
  - lokic
  - story_type
  - cron_tab
  - scrape_task
  - article_type

:schedule:
  initial:
    in: '0s'
    queue: cron_tab
    class: CronTabInitializerJob
